Repository Foxterosa/Vesta.Bay, pull requests merged in 2021-01, with the labels that each got.

#24 Exploradores con permiso de conducción
  maps/torch/job/exploration_jobs.dm
Labels: :bulb: Feature

#23 Amabilia (Gafas Aesthetic)
  baystation12.dme
  code/modules/client/preference_setup/loadout/lists/eyegear.dm
  manaos/code/modules/clothing/glasses/sunglasses.dm
  manaos/icons/mob/onmob/onmob_eyes.dmi
  manaos/icons/obj/clothing/obj_eyes.dmi
Labels: :bulb: Feature, Sprites

#21 Añade un chaleco attacheable al loadout.
  code/modules/client/preference_setup/loadout/lists/tactical.dm
Labels: Sprites
